---
# System Updates
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Upgrade all packages
  apt:
    upgrade: full
    autoclean: yes
    autoremove: yes
  become: true

- name: Install common dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg
    state: present
  become: true
