- name: Download AWS CLI installer
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Unzip AWS CLI installer
  shell: unzip awscliv2.zip

- name: Install AWS CLI
  shell: sudo ./aws/install
