---
# Install Terraform
- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Add HashiCorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    filename: hashicorp
  become: true

- name: Install Terraform
  apt:
    name: terraform
    state: present
    update_cache: yes
  become: true
