- name: Setup Homeserver Environment
  hosts: all
  become: true
  roles:
    # # System setup and common dependencies
    # - common

    # Basic development tools
    - development-tools

    # Container tools
    - docker-tools

    # Kubernetes and related tools
    - kubernetes-tools

    # Cloud tools
    - cloud-tools
